import {iconGallery, iconScroll,avatar} from '../assets';
export const listHardCode = [
  {
    id: 1,
    nameProject: 'Beautiful Gallery View - Pexels API',
    icon: iconGallery,
    navigation: 'GalleryView',
  },
  {
    id: 2,
    nameProject: 'Scroll Items Animation Effect',
    icon: iconScroll,
    navigation: 'ScrollItems',
  },
  {
    id: 3,
    nameProject: 'Beautiful Gallery View - Pexels API',
    icon: iconGallery,
    navigation: 'GalleryView',
  },
  {
    id: 4,
    nameProject: 'Beautiful Gallery View - Pexels API',
    icon: iconGallery,
    navigation: 'GalleryView',
  },
  {
    id: 1,
    nameProject: 'Beautiful Gallery View - Pexels API',
    icon: iconGallery,
    navigation: 'GalleryView',
  },
  {
    id: 2,
    nameProject: 'Beautiful Gallery View - Pexels API',
    icon: iconGallery,
    navigation: 'GalleryView',
  },
  {
    id: 3,
    nameProject: 'Beautiful Gallery View - Pexels API',
    icon: iconGallery,
    navigation: 'GalleryView',
  },
  {
    id: 4,
    nameProject: 'Beautiful Gallery View - Pexels API',
    icon: iconGallery,
    navigation: 'GalleryView',
  },
];
export const listAvatar = [
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
];
