import {iconGallery, iconScroll,avatar,iconLessons,iconRocket,iconMaps} from '../assets';
export const listHardCode = [
  {
    id: 1,
    nameProject: 'Animations Properties',
    icon: iconRocket,
    navigation: 'AnimationsProperties',
  },
  {
    id: 2,
    nameProject: 'Scroll Items Animation Effect',
    icon: iconScroll,
    navigation: 'ScrollItems',
  },
  {
    id: 3,
    nameProject: 'Lessons William Candillon',
    icon: iconLessons,
    navigation: 'Lessons',
  },
  {
    id: 4,
    nameProject: 'Beautiful Gallery View - Pexels API',
    icon: iconGallery,
    navigation: 'GalleryView',
  },
  {
    id: 5,
    nameProject: 'Maps',
    icon: iconMaps,
    navigation: 'Maps',
  },
];
export const listAvatar = [
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
  {
    name: 'Mr Hung',
    jobTitle: 'Mobile Developer',
    email: 'hungk.dev@gmail.com',
    avatar: avatar,
  },
];
